version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tools/docker
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /tools/docker
    schedule:
      interval: daily
